### ISSUE TITLE
ValueError: '_buffers' is not a parameter of PolyEdit08625 in "High Resolution Matrix Export"?

### ISSUE THREAD

**Issue by Li-ZhiD** [STOmics/Stereopy#199]
Error below when I want lasso area from raw STO data?

Traceback (most recent call last):
  File "/home/robot/.local/lib/python3.8/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/home/robot/.local/lib/python3.8/site-packages/holoviews/plotting/bokeh/callbacks.py", line 155, in on_msg
    stream.update(**processed_msg)
  File "/home/robot/.local/lib/python3.8/site-packages/holoviews/streams.py", line 441, in update
    self._set_stream_parameters(**kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/holoviews/streams.py", line 422, in _set_stream_parameters
    self.param.set_param(**kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/param/parameterized.py", line 1925, in set_param
    return self_.update(kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/param/parameterized.py", line 1889, in update
    raise ValueError("'%s' is not a parameter of %s" % (k, self_or_cls.name))
ValueError: '_buffers' is not a parameter of PolyEdit08625

**Comment by Zhenbin24** [comment]
hello, For software version issues, execute directly: pip install pyviz-comms==2.2.1  -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by Li-ZhiD** [comment]
I reinstalled pyviz-comms==2.2.1. Despite no error information occurring, nothing was obtained after clicking the 'export' button.

**Comment by Zhenbin24** [comment]
The example in this article（https://stereopy.readthedocs.io/en/latest/Tutorials/Interactive_Cluster.html） is missing a step ins.add_select_area()；
![image](https://github.com/STOmics/Stereopy/assets/33947214/ceaf58a7-b4c5-478c-88a5-a7a61cbcebca)

It is recommended to refer to this article for examples：https://stereopy.readthedocs.io/en/latest/Tutorials/High_Resolution_Export.html
