### ISSUE TITLE
stereopy read_gef got an error : UnicodeDecodeError

### ISSUE THREAD

**Issue by shanhuhai-i** [STOmics/Stereopy#333]
hi,

read tissue.gef by bin_size, error message:

Thank you~

`[reader][897][INFO]: read_gef begin ...
[reader][984][INFO]: the matrix has 90000 cells, and 20000 genes.
Traceback (most recent call last):
  File "square.bin.py", line 35, in <module>
    data = st.io.read_gef(file_path=gef_path,bin_size=20,is_sparse=True) 
  File "../python3.8/site-packages/stereo/utils/read_write_utils.py", line 37, in wrapped
    return func(*args, **kwargs)
  File ../python3.8/site-packages/stereo/io/reader.py", line 985, in read_gef
    cols, uniq_genes = gef.get_gene_data()
  File "gefpy/bgef_reader_cy.pyx", line 105, in gefpy.bgef_reader_cy.BgefR.get_gene_data
  File "stringsource", line 61, in vector.to_py.__pyx_convert_vector_to_py_std_3a__3a_string
  File "stringsource", line 38, in string.to_py.__pyx_convert_PyUnicode_string_to_py_std__in_string
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 1: invalid start byte`

**Comment by Learnerhua** [comment]
So, how to resolve this issue finally ?

**Comment by Japrin** [comment]
the same issue
