### ISSUE TITLE
ValueError: The number of threads must be between 1 and 32

### ISSUE THREAD

**Issue by ASasasdasfasfasfasfasf** [STOmics/Stereopy#362]
import stereo as st
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

# read data
input_file = './C04042E2/outs/analysis/C04042E2.cellbin_1.0.h5ad'
data = st.io.read_h5ad(input_file, spatial_key='spatial')

# preprocessing
data.tl.cal_qc()
data.tl.filter_cells(min_counts=300, pct_counts_mt=10)
data.tl.filter_genes(min_cells=10)

# save raw data
data.tl.raw_checkpoint()

data.tl.normalize_total(target_sum=10000)
data.tl.log1p()

# PCA
data.tl.pca(use_highly_genes=False, n_pcs=50, svd_solver='arpack')

# Gaussian smoothing
data.tl.gaussian_smooth(n_neighbors=10, smooth_threshold=90)
data.tl.scale(max_value=10) # only for gaussian_smooth_scatter_by_gene

# plot
data.plt.gaussian_smooth_scatter_by_gene(gene_name='C1ql2')
data.plt.gaussian_smooth_scatter_by_gene(gene_name='Irx2')
data.plt.gaussian_smooth_scatter_by_gene(gene_name='Calb1')

Traceback (most recent call last):
  File "process_gau.py", line 25, in <module>
    data.tl.gaussian_smooth(n_neighbors=10, smooth_threshold=90)
  File "/public1/home/a8s000127/miniforge3/envs/st/lib/python3.8/site-packages/stereo/core/st_pipeline.py", line 43, in wrapped
    res = func(*args, **kwargs)
  File "/public1/home/a8s000127/miniforge3/envs/st/lib/python3.8/site-packages/stereo/core/st_pipeline.py", line 1462, in gaussian_smooth
    result = gaussian_smooth(
  File "/public1/home/a8s000127/miniforge3/envs/st/lib/python3.8/site-packages/stereo/algorithm/gaussian_smooth.py", line 115, in gaussian_smooth
    nb.set_num_threads(n_jobs)
  File "/public1/home/a8s000127/miniforge3/envs/st/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 607, in set_num_threads
    snt_check(n)
  File "/public1/home/a8s000127/miniforge3/envs/st/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 569, in snt_check
    raise ValueError(msg)
ValueError: The number of threads must be between 1 and 32

**Comment by jianghao0799** [comment]
Hi, @xiaoxiaoniao666 
I ran into the same problem as you. How did you solve it?
